apiVersion: v1
kind: Service
metadata:
  name: cloud-l3-service1
spec:
  ports:
    - name: "8080"
      port: 8081
      targetPort: 8080
  selector:
    app: cloud-l3-project
  type: LoadBalancer
#  type: ClusterIP
